[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.3"
  BASE_URL = "https://sensornode.shop"
  BUN_INSTALL = "/opt/buildhome/.bun"
  BUN_BIN = "/opt/buildhome/.bun/bin"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
